apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spectrawatt-tls
  namespace: spectrawatt
spec:
  secretName: spectrawatt-tls
  dnsNames:
    - api.spectrawatt.upayan.dev
    - ai.spectrawatt.upayan.dev
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
