apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spectrawatt-ingress
  namespace: spectrawatt
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-http
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-entry-point: websecure
spec:
  tls:
    - hosts:
        - api.spectrawatt.upayan.dev
        - ai.spectrawatt.upayan.dev
      secretName: spectrawatt-tls
  rules:
    - host: api.spectrawatt.upayan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spectrawatt-api
                port:
                  number: 8080
    - host: ai.spectrawatt.upayan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spectrawatt-ai
                port:
                  number: 8000
